const copy = {
  quietHours: ['安静时段', 'Quiet hours'],
  quietHoursNote: ['开始与结束相同表示关闭。跨午夜的时段会延续到次日。', 'Matching start and end times disables quiet hours. Overnight hours continue into the next day.'],
  preferenceError: ['未能保存设置，请重试。', 'Could not save this setting. Try again.'],
  push: ['远程推送', 'Remote push'],
  pushRequest: ['连接此设备', 'Connect this device'],
  pushUnconfigured: ['当前构建未配置推送项目。', 'This build has no push project configured.'],
  pushTokenReady: ['已取得设备推送令牌，尚未确认远端注册。', 'Device push token obtained. Remote registration is not confirmed.'],
  pushRegistered: ['远端已确认此设备注册。尚未验证推送送达。', 'Remote registration confirmed. Push delivery has not been verified.'],
  pushError: ['推送连接未完成，请检查权限、网络与构建配置后重试。', 'Push setup did not complete. Check permissions, network and build configuration, then retry.'],
  pushIdle: ['设备推送令牌、远端注册与实际送达分别验证。', 'Device token, remote registration and delivery are verified separately.'],
  calendarSeparate: ['系统日历事件需单独确认写入、修改或删除；修改此计划不会自动更改系统日历。', 'System-calendar events require a separate confirmed write, edit or deletion. Changing this plan does not automatically change the system calendar.'],
  nativeExportScope: ['导出当前应用记录的 JSON 文件，不是完整设备备份。不含登录凭据、同步队列、设备权限或原始设备来源库。恢复账号记录请使用账号与同步。', 'Export current app records as a JSON file, not a full device backup. Credentials, sync queues, device permissions and the raw device-source repository are excluded. Use Account & Sync to recover account records.'],
  nativeExportConfirm: ['未加密的文件可能包含私人记录和健康相关上下文。请选择可信的接收位置；接收 App 可能将内容上传。临时文件保留在应用缓存，后续导出会清理超过一天的临时副本。本操作不清除记录或退出账号。继续？', 'The unencrypted file may contain private records and Health-related context. Choose a trusted destination; the receiving app may upload it. A temporary app-cache copy remains; later exports remove copies older than one day. This action does not clear records or sign out. Continue?'],
  nativeExportResult: ['JSON 文件已生成，系统分享面板已返回；不代表接收位置已保存。请核实目标位置，取消分享也不会清除应用记录。', 'The JSON file was created and the share sheet returned. This does not confirm that the destination saved it. Check the destination; cancelling sharing does not clear app records.'],
  nativeExportCancelled: ['已取消分享，记录未更改。', 'Sharing cancelled. Records are unchanged.'],
  nativeExportFailed: ['未能完成文件导出，应用记录未更改。请检查设备空间与可用分享 App 后重试。', 'File export did not complete. App records are unchanged. Check device storage and available sharing apps, then retry.'],
  nativeExportUnavailable: ['此设备或构建不支持文件分享，未导出。Web 设置提供 JSON 文件下载。', 'File sharing is unavailable on this device or build. Nothing was exported. Web Settings provides a JSON file download.'],
  localClearScope: ['账号与同步中的清除入口仅在退出登录且保留原账号绑定时显示；不会自动退出。只清除本机记录与健康副本，不删除云端、系统日历或系统健康数据。未绑定账号的本地数据暂无清除入口。', 'Account & Sync shows the clear action only while signed out with an existing account binding; it never signs you out automatically. It removes local record and Health copies, not cloud, system Calendar or system Health data. Unbound local data has no clear entry.'],
  calendarAppPlan: ['当前应用计划', 'Current app plan'],
  calendarAccountSeparate: ['此处显示本机应用当前计划，包括已收到的账号更新；账号同步结果请查看设置，不代表系统日历已更新。', 'This is the current app plan, including received account updates. Account sync status is shown in Settings; it does not confirm a device-calendar write.'],
  calendarDeviceStatus: ['此设备的系统日历', 'System calendar on this device'],
  calendarChecking: ['正在读取写入状态…', 'Reading write status...'],
  calendarNotExported: ['尚未写入此日历', 'Not written to this calendar'],
  calendarCurrent: ['与上次确认的设备日历写入一致', 'Matches the last confirmed device-calendar write'],
  calendarNeedsReview: ['计划或日历绑定已变化，请查看后确认写入。', 'The plan or calendar binding changed. Review before confirming a write.'],
  calendarPending: ['已确认的日历操作待处理，不代表已写入。', 'A confirmed calendar operation is pending, not yet a confirmed write.'],
  calendarRetryStatus: ['上次日历操作未完成，可重试已确认的操作。', 'The calendar operation did not complete. Retry the confirmed operation.'],
  calendarAmbiguous: ['无法确认事件绑定。请检查系统日历；不会自动创建替代事件。', 'The event binding is uncertain. Check the system calendar; no replacement event will be created automatically.'],
  calendarInactive: ['此日历绑定已停用，请先在设置中检查日历连接。', 'This calendar binding is inactive. Check the calendar connection in Settings first.'],
  calendarDeleted: ['此前的日历事件已删除；再次写入需要确认。', 'The previous calendar event was deleted. Writing again requires confirmation.'],
  calendarLastWrite: ['上次确认写入', 'Last confirmed write'],
  calendarRetry: ['重试已确认的日历操作', 'Retry confirmed calendar operation'],
  calendarRetryDelete: ['重试已确认的日历删除', 'Retry confirmed calendar deletion'],
  calendarRetryDeleteConfirm: ['重试此前已确认的系统日历事件删除。不会删除应用计划或云端记录。继续？', 'Retry the previously confirmed system-calendar event deletion. This does not delete the app plan or cloud records. Continue?'],
  calendarWrite: ['确认写入日历', 'Confirm calendar write'],
  calendarWriteConfirm: ['将此处所示计划写入所选系统日历，或重试此前确认的同一计划。此操作不确认账号同步，也不会自动写入后续计划变化。继续？', 'Write the plan shown here to the selected system calendar, or retry that same previously confirmed plan. This does not confirm account sync or automatically export later plan changes. Continue?'],
  calendarPlanChanged: ['计划已变化，未提交日历写入。请查看当前计划后重新确认。', 'The plan changed. No calendar write was submitted. Review the current plan and confirm again.'],
} as const;

export function workflowCopy(lang: 'zh' | 'en', key: keyof typeof copy) {
  return copy[key][lang === 'zh' ? 0 : 1];
}
