import type { Lang } from '../../i18n';

const strings = {
  title: ['个人观察', 'Personal observations'],
  load: ['读取个人分析', 'Load my analysis'],
  refresh: ['刷新分析', 'Refresh analysis'],
  idle: ['个人分析尚未读取', 'Your analysis has not been loaded'],
  consent: ['仅在你点击读取或刷新时，将合格观察发送到已配置的 QuestLife 分析服务。', 'Eligible observations are sent to the configured QuestLife analysis service only when you load or refresh.'],
  empty: ['暂无合格的个人观察', 'No eligible personal observations yet'],
  emptyBody: ['已有记录保持不变。可继续在今日记录状态与实际执行，或在设置中连接来源。', 'Existing records are unchanged. Record state and actual execution in Today, or connect sources in Settings.'],
  serviceError: ['分析服务未能返回可用结果', 'The analysis service could not return a usable result'],
  serviceErrorBody: ['这不是数据不足的判断。请重试；已有记录没有改变。', 'This is not a finding of insufficient data. Retry; existing records have not changed.'],
  accountSetup: ['账户连接尚未配置', 'Account connection is not configured'],
  accountSetupBody: ['此构建尚不能读取需登录的个人分析。已有记录保持不变；这不表示没有观察数据。', 'This build cannot yet load account-protected analysis. Existing records are unchanged; this does not mean observations are missing.'],
  signIn: ['请先登录账户', 'Sign in to load personal analysis'],
  signInBody: ['请在设置中完成登录，再重新读取。不会将未登录状态当作无数据。', 'Complete sign-in in Settings, then retry. Being signed out is not treated as having no data.'],
  accountChanged: ['账户或数据授权需要确认', 'Account or data consent needs attention'],
  accountChangedBody: ['请在设置中检查当前账户、同步状态和数据授权，再重新读取。旧账户的结果不会继续展示。', 'Check the current account, sync state and data consent in Settings, then retry. Results from a previous account are not retained.'],
  retained: ['正在展示上一次成功读取的结果', 'Showing the last successfully loaded result'],
  stale: ['上游将此结果标记为过期', 'This result is marked stale by the source'],
  unknownFreshness: ['上游未确认此结果的新鲜度', 'Result freshness is not confirmed by the source'],
  changed: ['记录已更新，请重新读取分析', 'Records changed. Load analysis again'],
  chartError: ['图表未能加载。原始记录与证据仍可查看。', 'The chart could not load. Observations and evidence remain available.'],
  retryChart: ['重新加载图表', 'Reload chart'],
  chartLoading: ['正在加载本地图表', 'Loading local chart'],
  chartReady: ['图表已就绪', 'Chart ready'],
  fit: ['复位可见范围', 'Reset visible range'],
  custom: ['自定义范围', 'Custom range'],
  invalidCount: ['请输入大于零的整数', 'Enter a positive whole number'],
  invalidDates: ['请选择有效且起止顺序正确的日期', 'Choose valid dates in chronological order'],
  dateFormat: ['年-月-日', 'YYYY-MM-DD'],
  noRangePoints: ['这个范围内没有观察', 'No observations in this range'],
  noRangeCandle: ['这个范围未提供合格的上游 OHLC；请选择其他范围或视图。', 'No eligible upstream OHLC was supplied for this range. Choose another range or view.'],
  noSeries: ['上游尚未提供此变量的完整时间序列', 'A full time series has not been supplied for this variable'],
  rangeWindow: ['图表时间范围', 'Chart time window'],
  comparisonLimit: ['最多选择三个对比变量', 'Select up to three comparison variables'],
  incompatible: ['单位或量表不同，不能共用纵轴', 'Different unit or scale; cannot share this axis'],
  incompatibleMethod: ['测量方法不同，不可直接叠加', 'Different measurement methods; cannot overlay'],
  noComparisonPoints: ['当前主变量时间范围内无可用观察', 'No observations in the primary time window'],
  comparisonScope: ['比较使用主变量的时间范围；不归一化、不补值，也不推断相关性。', 'Comparison uses the primary time window, with no normalization, imputation or inferred correlation.'],
  history: ['观察明细', 'Observations'],
  showMore: ['显示更多', 'Show more'],
  source: ['来源', 'Source'],
  method: ['上游方法', 'Source method'],
  unit: ['单位', 'Unit'],
  scale: ['量表', 'Scale'],
  status: ['状态', 'Status'],
  reasonCodes: ['上游限制代码', 'Source limitation codes'],
  none: ['未提供', 'Not supplied'],
  rangeCount: ['当前显示 {count} 条观察', '{count} observations in view'],
  sample: ['示例数据', 'Example data'],
  sampleBody: ['隔离的只读示例，不属于你的账户，也不会写入记录、同步队列或通知。', 'An isolated read-only example, not your account. Nothing is written to records, sync queues or notifications.'],
  sampleOpen: ['浏览示例', 'Explore examples'],
  sampleExit: ['返回个人数据', 'Return to my data'],
  sampleError: ['示例产物未能通过校验或加载失败', 'Example artifacts could not be validated or loaded'],
  single: ['单次观察', 'Single observation'],
  mature: ['较完整历史', 'Established history'],
  analysisMismatch: ['附加分析与当前数据不匹配，已隐藏；基础观察仍可用。', 'Additional analysis does not match this dataset and is hidden. Base observations remain available.'],
  targetMismatch: ['这项分析属于另一个变量', 'This analysis belongs to another variable'],
  analyzeTarget: ['查看分析目标', 'View analysis target'],
  noAnalysis: ['上游未提供这项分析，仍可探索原始观察。', 'This analysis was not supplied. Raw observations remain available.'],
  analysisWindowNote: ['以下分析使用上游列出的窗口，不会随图表缩放重新计算。', 'Analysis uses the source window shown below; chart zoom does not recompute it.'],
  events: ['范围内事件', 'Events in range'],
  missing: ['缺失记录', 'Missing observations'],
  provenance: ['数据追溯', 'Provenance'],
  referenceRange: ['参考下界 / 上界', 'Reference lower / upper'],
  referenceStatus: ['参考状态', 'Reference status'],
  parameter: ['参数', 'Parameter'],
  bundle: ['产物', 'Artifact'],
  measuredAt: ['观察时间', 'Observed at'],
  localTime: ['时间按本机时区显示', 'Times shown in device time zone'],
  hiddenUnavailable: ['当前没有可用的指标层', 'No indicator layers are available'],
  watchlistManage: ['编辑自选指标', 'Edit watchlist'],
  allVariables: ['全部变量', 'All variables'],
  month: ['月', 'Month'], quarter: ['季度', 'Quarter'], halfYear: ['半年', 'Half year'], year: ['年', 'Year'],
  deviceReadError: ['设备来源读取失败；本次仅使用当前可读取的数据。', 'Device sources could not be read; only currently readable data is used.'],
} as const;

export type NativeInsightsStringKey = keyof typeof strings;
export const nativeInsightsStringKeys = Object.keys(strings) as NativeInsightsStringKey[];
export function ni(lang: Lang, key: NativeInsightsStringKey, values: Record<string, string | number> = {}) {
  return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), strings[key][lang === 'zh' ? 0 : 1] as string);
}
